Added tests for Test::Mojo::content_* methods
mojolicious/mojo pull request #1591
Opened 2020-10-30 03:56 UTC by rage311

### Summary
Added Test::Mojo::content_* tests.  If it seems like I'm on the right path here, I can continue adding tests for more methods.

### Motivation
Part of addressing #1488 

### References
#1488

2020-10-30 15:39 UTC, kraih requested changes
Please squash your commits.

2020-11-01 12:43 UTC, kraih approved these changes

2020-11-02 10:27 UTC, jhthorsen approved these changes
Looks good to me 👍

2020-11-02 10:28 UTC, merged

2020-11-03 19:17 UTC, rage311 commented
Sorry to be a bother, as I realize this isn't your problem, but it seems these pull requests weren't counted toward Hacktoberfest as the hacktoberfest label was removed from the mojo project and they must not have done their validity checks before that happened.  In lieu of re-adding the hacktoberfest label to the project, it seems you can also add a `hacktoberfest-accepted` label to this pull request, which should also make it count.  If there's any chance that someone could add the `hacktoberfest-accepted` label to my 3 pull requests (#1592 and #1593 too), I would be very grateful.