Added Test::Mojo::attr_* tests
mojolicious/mojo pull request #1592
Opened 2020-10-30 05:14 UTC by rage311

### Summary
Added Test::Mojo::attr_* tests

### Motivation
Requested changes in #1488 

### References
#1488

2020-10-30 15:45 UTC, kraih requested changes
Please squash your commits.

2020-10-31 00:51 UTC, jhthorsen submitted a review, later dismissed
Looks good to me 👍

2020-11-01 12:42 UTC, kraih submitted a review, later dismissed

2020-11-02 10:37 UTC, kraih approved these changes

2020-11-02 10:50 UTC, jhthorsen approved these changes
Still okidoki 👍

2020-11-02 10:50 UTC, merged