Provide (empty) Mojo::Promise::AWAIT_CHAIN_CANCEL method
mojolicious/mojo pull request #1604
Opened 2020-11-09 10:11 UTC by leonerd

### Summary
Adds new named method for latest `Future::AsyncAwait::Awaitable` role API specification.

### Motivation
Future::AsyncAwait will expect this new name in a later version.

### References
https://metacpan.org/pod/Future::AsyncAwait::Awaitable#AWAIT_ON_CANCEL

2020-11-09 11:32 UTC, kraih requested changes

2020-11-09 11:32 UTC, kraih commented on lib/Mojo/Promise.pm
> +sub AWAIT_CHAIN_CANCEL { } # new name
Inconsistent comments.

2020-11-09 11:44 UTC, kraih commented on lib/Mojo/Promise.pm
> +sub AWAIT_CHAIN_CANCEL { } # new name
You also forgot to perltidy.

2020-11-09 12:30 UTC, leonerd commented on lib/Mojo/Promise.pm
> +sub AWAIT_CHAIN_CANCEL { } # new name
Updated.

2020-11-09 13:43 UTC, kraih commented on lib/Mojo/Promise.pm
> +sub AWAIT_CHAIN_CANCEL { }    # new name
Just get rid of thew comments.

2020-11-09 18:21 UTC, kraih commented on lib/Mojo/Promise.pm
> +sub AWAIT_CHAIN_CANCEL { }
Oops, i missed that the functions are not ordered alphabetical.

2020-11-10 00:32 UTC, kiwiroy commented
`pod_coverage.t` needs amending to fix the CI error.
https://github.com/mojolicious/mojo/blob/8a6b0037c94cae16ee97debf425091d1968b9063/t/pod_coverage.t#L10

2020-11-18 16:39 UTC, leonerd commented
> `pod_coverage.t` needs amending to fix the CI error.
> 
> https://github.com/mojolicious/mojo/blob/8a6b0037c94cae16ee97debf425091d1968b9063/t/pod_coverage.t#L10

Now fixed in 4f5a0dead

2020-11-18 16:46 UTC, kraih commented on t/pod_coverage.t
> +  qw(AWAIT_IS_CANCELLED AWAIT_IS_READY AWAIT_NEW_DONE AWAIT_NEW_FAIL),
We use line length 120.

2020-11-18 16:46 UTC, kraih commented
Please squash commits.

2020-11-18 17:22 UTC, leonerd commented
Rewrapped and squashed.

2020-11-18 18:07 UTC, Grinnz approved these changes

2020-11-18 18:23 UTC, jberger approved these changes

2020-11-18 18:24 UTC, merged