Document and test that Mojo::ByteStream split method uses core split function semantics
mojolicious/mojo pull request #1617
Opened 2020-11-28 20:22 UTC by Grinnz

### Summary
The first argument to Mojo::ByteStream's split method has some special treatment as it's passed directly to the split function. Add some documentation and examples to clarify this treatment - it's the pattern argument and is treated as a regex, except in the awk compatibility special case of a single space character, and the special case of an empty pattern which splits on each character.

It also may be worthwhile to suggest and document passing split patterns to this function as `qr//` regex refs rather than strings, thoughts? (this is already tested)

### Motivation
Clarify how this argument is interpreted.

### References
https://perldoc.perl.org/functions/split

2020-11-28 20:29 UTC, kraih approved these changes

2020-11-28 20:58 UTC, Grinnz commented
The split function only consistently interprets a string containing a single space when it's not a literal since 5.18: https://perldoc.perl.org/perl5180delta#split's-first-argument-is-more-consistently-interpreted

So added a workaround to make this work consistently on 5.16, the other option is not documenting or testing the single space string case at all.

2020-11-29 13:29 UTC, kraih commented on lib/Mojo/ByteStream.pm
> +  # awk compatible special case on 5.16
AWK.

2020-11-29 13:30 UTC, kraih requested changes
I'm opposed to adding special workarounds for Perl 5.16.

2020-11-29 13:32 UTC, kraih commented
For reference. https://docs.mojolicious.org/Mojolicious/Guides/FAQ#Which-versions-of-Perl-are-supported-by-Mojolicious

2020-12-06 16:41 UTC, kraih commented
A week should have been enough time for anyone who disagrees to speak up, so i'll close this PR as rejected.

2020-12-06 16:41 UTC, closed without merging