convert t/mojolicious/dispatcher_lite_app.t to use subtests
mojolicious/mojo pull request #1676
Opened 2021-01-27 19:41 UTC by markogrady1

### Summary
convert `t/mojolicious/dispatcher_lite_app.t` to use subtests

### Motivation
i want to contribute to using subtests throughout.

### References
discussion: #1520

2021-01-28 00:44 UTC, jhthorsen submitted a review, later dismissed
Does not look controversial at all.

2021-01-28 19:41 UTC, kraih requested changes
Please rebase to master for perltidy check.

2021-01-28 20:41 UTC, kraih approved these changes

2021-02-13 19:37 UTC, kraih approved these changes

2021-02-16 23:40 UTC, jhthorsen approved these changes

2021-02-16 23:41 UTC, merged