Created form multipart example
mojolicious/mojo pull request #1901
Opened 2022-01-07 01:26 UTC by PaulGWebster

### Summary
A minor addition to the examples/synopsis

### Motivation
I found it really difficult to get multipart working

### References
No references

### Problems
There is no way to make a working example of this that will just run, unless anyone knows a site anywhere that would accept such a payload, By the way I actually expect this pull to be denied, but I want to raise that a form multipart example should be included!

2022-01-07 16:54 UTC, kraih commented
Always squash your commits.

2022-01-07 16:56 UTC, kraih commented on lib/Mojo/UserAgent.pm
> +  # Form multipart post with both a local file and document within a string, accepting a json return
Lower case `post` and `json`? 🤨

2022-01-07 16:56 UTC, kraih commented on lib/Mojo/UserAgent.pm
> +  # Form multipart post with both a local file and document within a string, accepting a json return
`...accepting a JSON response`.

2022-01-07 16:57 UTC, kraih commented on lib/Mojo/UserAgent.pm
> +    "https://example.com/"
Inconsistent quotes.

2022-01-07 16:59 UTC, kraih commented
👎 from me i'm afraid. Not opposed to having more forma examples, but this doesn't look clean.

2022-01-07 21:35 UTC, PaulGWebster commented on lib/Mojo/UserAgent.pm
> +  );
What would the standard formatting look like so I may update it

2022-01-07 22:05 UTC, PaulGWebster commented on lib/Mojo/UserAgent.pm
> +    "https://example.com/"
Updated

2022-01-07 22:06 UTC, PaulGWebster commented on lib/Mojo/UserAgent.pm
> +  # Form multipart post with both a local file and document within a string, accepting a json return
Updated

2022-01-27 21:33 UTC, PaulGWebster commented
> 👎 from me i'm afraid. Not opposed to having more forma examples, but this doesn't look clean.

I updated all but one of your exceptions, the one I have not updated required your input

2022-02-22 07:57 UTC, kathackeray requested changes
@PaulGWebster

Your example code has improperly nested brackets (so throws an error when run).  I've slightly reformatted and commented your example to demonstrate:

```perl
my $tx = $ua->post(
  'https://example.com/' => {'Accept' => 'application/json'} => form =>
  {
    'file1' => {
        'content'   =>  '<?xml version="1.0"?><P ID="greeting">Hi!</P>',
        'type'      =>  'text/xml',
        'filename'  =>  'submit.xml'
    }
  } =>
  {
    'file2' => { # <-------------------------------------- whoops!!
      'file'      =>  '/some/file/somewhere.xml'
  }
);
```

As for the formatting, I've compared it to the other examples in the synopsis and the docs for [Mojo::UserAgent::Transactor](https://docs.mojolicious.org/Mojo/UserAgent/Transactor#tx), and I've had a go at reformatting your example below to see if it is more in keeping with expectations.  Note that I have removed the `Accept` header, as this seems to distract from the purpose of the example.  Also I have combined both parts into a single hashref.

```perl
# Form multipart POST with both a local file upload and document within a string
my $tx = $ua->post('http://localhost:3000/' => form => {
    file_upload => {
      file      => 'test-file.txt',
    },
    file_string => {
      content   => '<?xml version="1.0"?><p id="greeting">How do!</p>',
      type      => 'text/xml',
      filename  => 'submit.xml'
    }
  }
);
```

This doesn't have the project's perltidy rules applied, but I've noticed that other examples in the synopsis appear to have prioritised clarity over adherence to those rules.  If perltidy conformance is required for the example, it would look like this:

```perl
# Form multipart POST with both a local file upload and document within a string
my $tx = $ua->post(
  'http://localhost:3000/' => form => {
    file_upload => {file => 'test-file.txt',},
    file_string =>
      {content => '<?xml version="1.0"?><p id="greeting">How do!</p>', type => 'text/xml', filename => 'submit.xml'}
  }
);
```

I tested it against a local `netcat` server:

```shell
$ nc -kdl localhost 3000
POST / HTTP/1.1
Content-Type: multipart/form-data; boundary=FAnFX
Accept-Encoding: gzip
User-Agent: Mojolicious (Perl)
Host: localhost:3000
Content-Length: 268

--FAnFX
type: text/xml
Content-Disposition: form-data; name="file_string"; filename="submit.xml"

<?xml version="1.0"?><p id="greeting">How do!</p>
--FAnFX
Content-Disposition: form-data; name="file_upload"; filename="test-file.txt"

Hello there!

--FAnFX--
```

I hope this helps.

2023-05-24 20:41 UTC, closed without merging