Add support for QUERY verb
mojolicious/mojo pull request #1912
Opened 2022-02-01 19:50 UTC by rabbiveesh

### Summary
Add support for the new QUERY http verb.

### Motivation
It was discussed on IRC. Bleeding edge features are a good look

### References
I brought up [this article](https://evertpot.com/get-request-bodies/).

2022-02-01 19:53 UTC, jberger commented
I think for me the fact that mojo already supports any given method gives the flexibility to use bleeding edge features without having to codify them early. Until QUERY is standardized I'd be hesitant to add shortcut support. 👎 from me

2022-02-01 19:54 UTC, Grinnz commented
This would need to be documented, and marked as experimental

2022-02-02 01:45 UTC, kraih commented
Needs more work, but i like the feature. Been some time since we added something interesting from a bleeding edge spec.

2022-02-02 02:28 UTC, jberger commented
> Needs more work, but i like the feature. Been some time since we added something interesting from a bleeding edge spec.

If you're comfortable with the inclusion, I'll defer to your judgement. You're certainly more on the pulse of these things

2022-02-04 08:55 UTC, rabbiveesh commented
@kraih could you point me in the right direction? I'm not sure what you would like to be touched up

2022-02-04 15:04 UTC, kraih requested changes

2022-02-04 15:04 UTC, kraih commented on lib/Mojolicious/Routes/Route.pm
> +L<Mojolicious::Guides::Routing> for more information. Note that this HTTP verb is B<EXPERIMENTAL> and might change without warning.
Method, not verb.

2022-02-04 15:04 UTC, kraih commented on lib/Mojolicious/Lite.pm
> +This HTTP verb is part of L<a draft RFC|https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html>, which is still a work in progress.
Line length.

2022-02-04 15:04 UTC, kraih commented on lib/Mojo/UserAgent.pm
> +perform requests non-blocking.
Why no spec link here?

2022-02-04 15:04 UTC, kraih commented on lib/Mojolicious/Lite.pm
> +Note that this HTTP verb is B<EXPERIMENTAL> and might change without warning.
Line length.

2022-02-04 15:04 UTC, kraih commented on lib/Mojolicious/Routes/Route.pm
> +L<Mojolicious::Guides::Routing> for more information. Note that this HTTP verb is B<EXPERIMENTAL> and might change without warning.
Line length.

2022-02-04 15:04 UTC, kraih commented on lib/Mojolicious/Routes/Route.pm
> +This HTTP verb is part of L<a draft RFC|https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html>, which is still a work in progress.
Line length.

2022-02-04 15:04 UTC, kraih commented on lib/Test/Mojo.pm
> +for the callback. Note that this HTTP verb is B<EXPERIMENTAL> and might change without warning.
Method, not verb.

2022-02-04 15:04 UTC, kraih commented on lib/Test/Mojo.pm
> +This HTTP verb is part of L<a draft RFC|https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html>, which is still a work in progress.
Line length.

2022-02-04 15:04 UTC, kraih commented on t/mojolicious/lite_app.t
> +$t->query_ok('/echojson', json => {message => {an => [qw/object of sorts/]}})->json_is('/an' => [qw/object of sorts/]);
You can also test with another method to make sure it's not just an `any` route.

2022-02-04 15:04 UTC, kraih commented on lib/Mojo/UserAgent.pm
> +perform requests non-blocking.
Method seems untested.

2022-02-04 15:04 UTC, kraih commented on lib/Mojo/UserAgent.pm
> +callback.
Also seems untested.

2022-03-04 16:07 UTC, kraih commented
PR seems abandoned. Given our growing review backlog, i'm closing this to make room for other PRs.

2022-03-04 16:07 UTC, closed without merging

2022-03-05 17:23 UTC, rabbiveesh commented
That's fair, I'll reopen it with the changes when I get time

On Fri, Mar 4, 2022, 18:08 Sebastian Riedel ***@***.***>
wrote:

> Closed #1912 <https://github.com/mojolicious/mojo/pull/1912>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mojolicious/mojo/pull/1912#event-6186153016>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFURPKQHFUNB3O6RD35QFFLU6IYOVANCNFSM5NKDL5EA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>